name: PMD Source Code Analyzer on Push
on:
  push:
    branches:
      - branch1-DevLocal

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes remotes::system_requirements("ubuntu", "20.04","myfunctionname") category/apex/design.xml -f text
