name: Run SFDX Scanner
on:
  push:
    paths:
      - force-app/**
  
jobs:
  scan-files:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install SFDX CLI and Scanner
    run: |
      npm install --global sfdx-cli
      sfdx --version
      sfdx plugins install @salesforce/sfdx-scanner - name: Apex static analysis
    run: |
      sfdx scanner run --target "force-app" -f junit
