name: scan-code
on: [push]
jobs:
  apex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup PMD
      uses: legetz/setup-pmd@7.1.0
    - name: APEX full scan for design rules only
      run: pmd check --dir /branch1-DevLocal/bookingsProject/force-app/main/default/classes -R /branch1-DevLocal/rulesets/apex_ruleset.xml -f text
