name: validate-apex-code
on:
  push:
    branches:
      - branch1-DevLocal
jobs:
  check-apex:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check APEX'
        uses: actions/checkout@v2
      - name: 'install PMD'
        run: |
          PMD_VERSION= cat pmd/pmd-version.txt
          wget wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.3.0/pmd-dist-7.3.0-bin.zip
          unzip pmd-bin-$PMD_VERSION.zip -d ~
          my ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/run.shipmd --version
      #Run Pmd
      - name: 'Run PMD scan'
        run: 
           ~/pmd/bin/run.sh pmd -d force-app -R ruleset/apex_ruleset.xml -f text
